version: '2'
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - "13306:3306"
    command: mysqld --character_set_server=utf8
    restart: always
    volumes:
#      - ./mysql/volumes:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample
      MYSQL_USER: sample
      MYSQL_PASSWORD: sample
      COMPOSE_CONVERT_WINDOWS_PATHS: 1